name: CI workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.dockerignore'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18.8.0'] 

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1 
      DATABASE_MARIADB_STABLE_URL: "mysql://root:root@localhost:4306/PRISMA_DB_NAME"
      DATABASE_MARIADB_BUGGED_URL: "mysql://root:root@localhost:4307/PRISMA_DB_NAME"
      DATABASE_MYSQL_URL: "mysql://root:root@localhost:3306/PRISMA_DB_NAME"

    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v3

      - name: Run docker/docker-compose.yml
        run: docker-compose -f docker/docker-compose.yml up -d

      - name: User Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Test bugged MariaDB
        run: |
          npm run prisma:db-push
          npm run test 
        env:
          DATABASE_URL: ${{ env.DATABASE_MARIADB_BUGGED_URL }}
          IS_DATABASE_BUGGED: '1'

      - name: Test stable MariaDB
        run: |
          npm run prisma:db-push
          npm run test 
        env:
          DATABASE_URL: ${{ env.DATABASE_MARIADB_STABLE_URL }}
